dynamic: install


all: install


install:
	cp -f libwlbcmcrypto.so_VIPER_IPV6_save $(INSTALL_DIR)/lib/libwlbcmcrypto.so
	cp -f libwlbcmshared.so_VIPER_IPV6_save $(INSTALL_DIR)/lib/libwlbcmshared.so
	cp -f libwlupnp.so_VIPER_IPV6_save $(INSTALL_DIR)/lib/libwlupnp.so
	cp -f eapd_VIPER_IPV6_save $(INSTALL_DIR)/bin/eapd
	cp -f lld2d_VIPER_IPV6_save $(INSTALL_DIR)/bin/lld2d
	cp -f wrt54g.large.ico_VIPER_IPV6_save $(INSTALL_DIR)/etc/wrt54g.large.ico
	cp -f wrt54g.small.ico_VIPER_IPV6_save $(INSTALL_DIR)/etc/wrt54g.small.ico
	cp -f nas_VIPER_IPV6_save $(INSTALL_DIR)/bin/nas
	cp -f nvram_VIPER_IPV6_save $(INSTALL_DIR)/bin/nvram
	cp -f libnvram.so_VIPER_IPV6_save $(INSTALL_DIR)/lib/libnvram.so
	cp -f nvram_params_VIPER_IPV6_save $(INSTALL_DIR)/etc/wlan/nvram_params
	cp -f nvramUpdate_VIPER_IPV6_save $(INSTALL_DIR)/bin/nvramUpdate
	cp -f wlctl_VIPER_IPV6_save $(INSTALL_DIR)/bin/wlctl
	cp -f libwlctl.so_VIPER_IPV6_save $(INSTALL_DIR)/lib/libwlctl.so
	cp -f wlmngr_VIPER_IPV6_save $(INSTALL_DIR)/bin/wlmngr
	cp -f wlevt_VIPER_IPV6_save $(INSTALL_DIR)/bin/wlevt
	cp -f libwlmngr.so_VIPER_IPV6_save $(INSTALL_DIR)/lib/libwlmngr.so
	cp -f libwlcsm.so_VIPER_IPV6_save $(INSTALL_DIR)/lib/libwlcsm.so
	cp -f wps_monitor_VIPER_IPV6_save $(INSTALL_DIR)/bin/wps_monitor
	cp -f libwps.so_VIPER_IPV6_save $(INSTALL_DIR)/lib/libwps.so
	cp -f epi_ttcp_VIPER_IPV6_save $(INSTALL_DIR)/bin/epi_ttcp
