/*
* <:copyright-BRCM:2012:DUAL/GPL:standard
* 
*    Copyright (c) 2012 Broadcom Corporation
*    All Rights Reserved
* 
* This program is free software; you can redistribute it and/or modify
* it under the terms of the GNU General Public License, version 2, as published by
* the Free Software Foundation (the "GPL").
* 
* This program is distributed in the hope that it will be useful,
* but WITHOUT ANY WARRANTY; without even the implied warranty of
* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
* GNU General Public License for more details.
* 
* 
* A copy of the GPL is available at http://www.broadcom.com/licenses/GPLv2.php, or by
* writing to the Free Software Foundation, Inc., 59 Temple Place - Suite 330,
* Boston, MA 02111-1307, USA.
* 
* :> 
*/

#ifndef __VOIP_H_INCLUDED
#define __VOIP_H_INCLUDED

/*  File automatically generated by Reggae at 09/08/2011  17:33:33   */

#include "stt_basic_defs.h"
#include "access_macros.h"
#include "packing.h"

/*****************************************************************************************/
/* DSP vblock                                                                            */
/*****************************************************************************************/

/*****************************************************************************************/
/* Blocks offsets                                                                        */
/*****************************************************************************************/
#define CE_VOIP_CFG_OFFSET	( 0x190A1400 )
/*****************************************************************************************/
/* Functions offsets and addresses                                                       */
/*****************************************************************************************/
#define CE_VOIP_CFG_MAILBOX_OFFSET 	( 0x00000000 )
#define CE_VOIP_CFG_MAILBOX_ADDRESS	( CE_VOIP_CFG_OFFSET + CE_VOIP_CFG_MAILBOX_OFFSET )

#define CE_VOIP_CFG_REGS_OFFSET 	( 0x00000080 )
#define CE_VOIP_CFG_REGS_ADDRESS	( CE_VOIP_CFG_OFFSET + CE_VOIP_CFG_REGS_OFFSET )

/*   'i' is block index    */
/*   'j' is function index */
/*   'e' is function entry */
/*   'k' is register index */

/*****************************************************************************************/
/* COM0                                                                                  */
/* Command 0 register                                                                    */
/*****************************************************************************************/

#define CE_VOIP_CFG_MAILBOX_COM0_RSV_DEFAULT_VALUE             ( 0x0 )
#define CE_VOIP_CFG_MAILBOX_COM0_RSV_DEFAULT_VALUE_RESET_VALUE ( 0x0 )
#define CE_VOIP_CFG_MAILBOX_COM0_COM_DEFAULT_VALUE             ( 0x0 )
#define CE_VOIP_CFG_MAILBOX_COM0_COM_DEFAULT_VALUE_RESET_VALUE ( 0x0 )


#define CE_VOIP_CFG_MAILBOX_COM0_OFFSET ( 0x00000000 )

#define CE_VOIP_CFG_MAILBOX_COM0_ADDRESS   	( CE_VOIP_CFG_MAILBOX_ADDRESS + CE_VOIP_CFG_MAILBOX_COM0_OFFSET )
#define BL_VOIP_CFG_MAILBOX_COM0_READ( r ) 	BL_READ_32( ( CE_VOIP_CFG_MAILBOX_COM0_ADDRESS ), (r) )
#define BL_VOIP_CFG_MAILBOX_COM0_WRITE( v )	BL_WRITE_32( ( CE_VOIP_CFG_MAILBOX_COM0_ADDRESS ), (v) )

typedef struct
{
	/* RSV */
	stt_uint32 rsv	: 16 __PACKING_ATTRIBUTE_FIELD_LEVEL__ ;

	/* COM */
	stt_uint32 com	: 16 __PACKING_ATTRIBUTE_FIELD_LEVEL__ ;
}
__PACKING_ATTRIBUTE_STRUCT_END__
VOIP_CFG_MAILBOX_COM0_DTE ;


/*****************************************************************************************/
/* COM1                                                                                  */
/* Command 1 register                                                                    */
/*****************************************************************************************/

#define CE_VOIP_CFG_MAILBOX_COM1_RSV_DEFAULT_VALUE             ( 0x0 )
#define CE_VOIP_CFG_MAILBOX_COM1_RSV_DEFAULT_VALUE_RESET_VALUE ( 0x0 )
#define CE_VOIP_CFG_MAILBOX_COM1_COM_DEFAULT_VALUE             ( 0x0 )
#define CE_VOIP_CFG_MAILBOX_COM1_COM_DEFAULT_VALUE_RESET_VALUE ( 0x0 )


#define CE_VOIP_CFG_MAILBOX_COM1_OFFSET ( 0x00000004 )

#define CE_VOIP_CFG_MAILBOX_COM1_ADDRESS   	( CE_VOIP_CFG_MAILBOX_ADDRESS + CE_VOIP_CFG_MAILBOX_COM1_OFFSET )
#define BL_VOIP_CFG_MAILBOX_COM1_READ( r ) 	BL_READ_32( ( CE_VOIP_CFG_MAILBOX_COM1_ADDRESS ), (r) )
#define BL_VOIP_CFG_MAILBOX_COM1_WRITE( v )	BL_WRITE_32( ( CE_VOIP_CFG_MAILBOX_COM1_ADDRESS ), (v) )

typedef struct
{
	/* RSV */
	stt_uint32 rsv	: 16 __PACKING_ATTRIBUTE_FIELD_LEVEL__ ;

	/* COM */
	stt_uint32 com	: 16 __PACKING_ATTRIBUTE_FIELD_LEVEL__ ;
}
__PACKING_ATTRIBUTE_STRUCT_END__
VOIP_CFG_MAILBOX_COM1_DTE ;


/*****************************************************************************************/
/* REP0                                                                                  */
/* Reply 0 register                                                                      */
/*****************************************************************************************/

#define CE_VOIP_CFG_MAILBOX_REP0_RSV_DEFAULT_VALUE             ( 0x0 )
#define CE_VOIP_CFG_MAILBOX_REP0_RSV_DEFAULT_VALUE_RESET_VALUE ( 0x0 )
#define CE_VOIP_CFG_MAILBOX_REP0_REP_DEFAULT_VALUE             ( 0x0 )
#define CE_VOIP_CFG_MAILBOX_REP0_REP_DEFAULT_VALUE_RESET_VALUE ( 0x0 )


#define CE_VOIP_CFG_MAILBOX_REP0_OFFSET ( 0x00000008 )

#define CE_VOIP_CFG_MAILBOX_REP0_ADDRESS   	( CE_VOIP_CFG_MAILBOX_ADDRESS + CE_VOIP_CFG_MAILBOX_REP0_OFFSET )
#define BL_VOIP_CFG_MAILBOX_REP0_READ( r ) 	BL_READ_32( ( CE_VOIP_CFG_MAILBOX_REP0_ADDRESS ), (r) )
#define BL_VOIP_CFG_MAILBOX_REP0_WRITE( v )	BL_WRITE_32( ( CE_VOIP_CFG_MAILBOX_REP0_ADDRESS ), (v) )

typedef struct
{
	/* RSV */
	stt_uint32 rsv	: 16 __PACKING_ATTRIBUTE_FIELD_LEVEL__ ;

	/* REP */
	stt_uint32 rep	: 16 __PACKING_ATTRIBUTE_FIELD_LEVEL__ ;
}
__PACKING_ATTRIBUTE_STRUCT_END__
VOIP_CFG_MAILBOX_REP0_DTE ;


/*****************************************************************************************/
/* REP1                                                                                  */
/* Reply 1 register                                                                      */
/*****************************************************************************************/

#define CE_VOIP_CFG_MAILBOX_REP1_RSV_DEFAULT_VALUE             ( 0x0 )
#define CE_VOIP_CFG_MAILBOX_REP1_RSV_DEFAULT_VALUE_RESET_VALUE ( 0x0 )
#define CE_VOIP_CFG_MAILBOX_REP1_REP_DEFAULT_VALUE             ( 0x0 )
#define CE_VOIP_CFG_MAILBOX_REP1_REP_DEFAULT_VALUE_RESET_VALUE ( 0x0 )


#define CE_VOIP_CFG_MAILBOX_REP1_OFFSET ( 0x0000000C )

#define CE_VOIP_CFG_MAILBOX_REP1_ADDRESS   	( CE_VOIP_CFG_MAILBOX_ADDRESS + CE_VOIP_CFG_MAILBOX_REP1_OFFSET )
#define BL_VOIP_CFG_MAILBOX_REP1_READ( r ) 	BL_READ_32( ( CE_VOIP_CFG_MAILBOX_REP1_ADDRESS ), (r) )
#define BL_VOIP_CFG_MAILBOX_REP1_WRITE( v )	BL_WRITE_32( ( CE_VOIP_CFG_MAILBOX_REP1_ADDRESS ), (v) )

typedef struct
{
	/* RSV */
	stt_uint32 rsv	: 16 __PACKING_ATTRIBUTE_FIELD_LEVEL__ ;

	/* REP */
	stt_uint32 rep	: 16 __PACKING_ATTRIBUTE_FIELD_LEVEL__ ;
}
__PACKING_ATTRIBUTE_STRUCT_END__
VOIP_CFG_MAILBOX_REP1_DTE ;


/*****************************************************************************************/
/* DSEM                                                                                  */
/* DSP semaphore register                                                                */
/*****************************************************************************************/

#define CE_VOIP_CFG_MAILBOX_DSEM_RSV_DEFAULT_VALUE             ( 0x0 )
#define CE_VOIP_CFG_MAILBOX_DSEM_RSV_DEFAULT_VALUE_RESET_VALUE ( 0x0 )
#define CE_VOIP_CFG_MAILBOX_DSEM_VAL_DEFAULT_VALUE             ( 0x0 )
#define CE_VOIP_CFG_MAILBOX_DSEM_VAL_DEFAULT_VALUE_RESET_VALUE ( 0x0 )


#define CE_VOIP_CFG_MAILBOX_DSEM_OFFSET ( 0x00000010 )

#define CE_VOIP_CFG_MAILBOX_DSEM_ADDRESS   	( CE_VOIP_CFG_MAILBOX_ADDRESS + CE_VOIP_CFG_MAILBOX_DSEM_OFFSET )
#define BL_VOIP_CFG_MAILBOX_DSEM_READ( r ) 	BL_READ_32( ( CE_VOIP_CFG_MAILBOX_DSEM_ADDRESS ), (r) )
#define BL_VOIP_CFG_MAILBOX_DSEM_WRITE( v )	BL_WRITE_32( ( CE_VOIP_CFG_MAILBOX_DSEM_ADDRESS ), (v) )

typedef struct
{
	/* RSV */
	stt_uint32 rsv	: 24 __PACKING_ATTRIBUTE_FIELD_LEVEL__ ;

	/* VAL */
	stt_uint32 val	: 8 __PACKING_ATTRIBUTE_FIELD_LEVEL__ ;
}
__PACKING_ATTRIBUTE_STRUCT_END__
VOIP_CFG_MAILBOX_DSEM_DTE ;


/*****************************************************************************************/
/* HSEM                                                                                  */
/* Host semaphore register                                                               */
/*****************************************************************************************/

#define CE_VOIP_CFG_MAILBOX_HSEM_RSV_DEFAULT_VALUE             ( 0x0 )
#define CE_VOIP_CFG_MAILBOX_HSEM_RSV_DEFAULT_VALUE_RESET_VALUE ( 0x0 )
#define CE_VOIP_CFG_MAILBOX_HSEM_VAL_DEFAULT_VALUE             ( 0x0 )
#define CE_VOIP_CFG_MAILBOX_HSEM_VAL_DEFAULT_VALUE_RESET_VALUE ( 0x0 )


#define CE_VOIP_CFG_MAILBOX_HSEM_OFFSET ( 0x00000014 )

#define CE_VOIP_CFG_MAILBOX_HSEM_ADDRESS   	( CE_VOIP_CFG_MAILBOX_ADDRESS + CE_VOIP_CFG_MAILBOX_HSEM_OFFSET )
#define BL_VOIP_CFG_MAILBOX_HSEM_READ( r ) 	BL_READ_32( ( CE_VOIP_CFG_MAILBOX_HSEM_ADDRESS ), (r) )
#define BL_VOIP_CFG_MAILBOX_HSEM_WRITE( v )	BL_WRITE_32( ( CE_VOIP_CFG_MAILBOX_HSEM_ADDRESS ), (v) )

typedef struct
{
	/* RSV */
	stt_uint32 rsv	: 24 __PACKING_ATTRIBUTE_FIELD_LEVEL__ ;

	/* VAL */
	stt_uint32 val	: 8 __PACKING_ATTRIBUTE_FIELD_LEVEL__ ;
}
__PACKING_ATTRIBUTE_STRUCT_END__
VOIP_CFG_MAILBOX_HSEM_DTE ;


/*****************************************************************************************/
/* HSEM_SET                                                                              */
/* Sets bits of host semaphore register                                                  */
/*****************************************************************************************/

#define CE_VOIP_CFG_MAILBOX_HSEM_SET_RSV_DEFAULT_VALUE             ( 0x0 )
#define CE_VOIP_CFG_MAILBOX_HSEM_SET_RSV_DEFAULT_VALUE_RESET_VALUE ( 0x0 )
#define CE_VOIP_CFG_MAILBOX_HSEM_SET_VAL_DEFAULT_VALUE             ( 0x0 )
#define CE_VOIP_CFG_MAILBOX_HSEM_SET_VAL_DEFAULT_VALUE_RESET_VALUE ( 0x0 )


#define CE_VOIP_CFG_MAILBOX_HSEM_SET_OFFSET ( 0x00000018 )

#define CE_VOIP_CFG_MAILBOX_HSEM_SET_ADDRESS   	( CE_VOIP_CFG_MAILBOX_ADDRESS + CE_VOIP_CFG_MAILBOX_HSEM_SET_OFFSET )
#define BL_VOIP_CFG_MAILBOX_HSEM_SET_READ( r ) 	BL_READ_32( ( CE_VOIP_CFG_MAILBOX_HSEM_SET_ADDRESS ), (r) )
#define BL_VOIP_CFG_MAILBOX_HSEM_SET_WRITE( v )	BL_WRITE_32( ( CE_VOIP_CFG_MAILBOX_HSEM_SET_ADDRESS ), (v) )

typedef struct
{
	/* RSV */
	stt_uint32 rsv	: 24 __PACKING_ATTRIBUTE_FIELD_LEVEL__ ;

	/* VAL */
	stt_uint32 val	: 8 __PACKING_ATTRIBUTE_FIELD_LEVEL__ ;
}
__PACKING_ATTRIBUTE_STRUCT_END__
VOIP_CFG_MAILBOX_HSEM_SET_DTE ;


/*****************************************************************************************/
/* HSEM_CLR                                                                              */
/* Clears bits of host semaphore register                                                */
/*****************************************************************************************/

#define CE_VOIP_CFG_MAILBOX_HSEM_CLR_RSV_DEFAULT_VALUE             ( 0x0 )
#define CE_VOIP_CFG_MAILBOX_HSEM_CLR_RSV_DEFAULT_VALUE_RESET_VALUE ( 0x0 )
#define CE_VOIP_CFG_MAILBOX_HSEM_CLR_VAL_DEFAULT_VALUE             ( 0x0 )
#define CE_VOIP_CFG_MAILBOX_HSEM_CLR_VAL_DEFAULT_VALUE_RESET_VALUE ( 0x0 )


#define CE_VOIP_CFG_MAILBOX_HSEM_CLR_OFFSET ( 0x0000001C )

#define CE_VOIP_CFG_MAILBOX_HSEM_CLR_ADDRESS   	( CE_VOIP_CFG_MAILBOX_ADDRESS + CE_VOIP_CFG_MAILBOX_HSEM_CLR_OFFSET )
#define BL_VOIP_CFG_MAILBOX_HSEM_CLR_READ( r ) 	BL_READ_32( ( CE_VOIP_CFG_MAILBOX_HSEM_CLR_ADDRESS ), (r) )
#define BL_VOIP_CFG_MAILBOX_HSEM_CLR_WRITE( v )	BL_WRITE_32( ( CE_VOIP_CFG_MAILBOX_HSEM_CLR_ADDRESS ), (v) )

typedef struct
{
	/* RSV */
	stt_uint32 rsv	: 24 __PACKING_ATTRIBUTE_FIELD_LEVEL__ ;

	/* VAL */
	stt_uint32 val	: 8 __PACKING_ATTRIBUTE_FIELD_LEVEL__ ;
}
__PACKING_ATTRIBUTE_STRUCT_END__
VOIP_CFG_MAILBOX_HSEM_CLR_DTE ;


/*****************************************************************************************/
/* HSTS                                                                                  */
/* Interface status                                                                      */
/*****************************************************************************************/

#define CE_VOIP_CFG_MAILBOX_HSTS_RSV_DEFAULT_VALUE                ( 0x0 )
#define CE_VOIP_CFG_MAILBOX_HSTS_RSV_DEFAULT_VALUE_RESET_VALUE    ( 0x0 )
#define CE_VOIP_CFG_MAILBOX_HSTS_DBUSY_DEFAULT_VALUE              ( 0x0 )
#define CE_VOIP_CFG_MAILBOX_HSTS_DBUSY_DEFAULT_VALUE_RESET_VALUE  ( 0x0 )
#define CE_VOIP_CFG_MAILBOX_HSTS_WRERR_DEFAULT_VALUE              ( 0x0 )
#define CE_VOIP_CFG_MAILBOX_HSTS_WRERR_DEFAULT_VALUE_RESET_VALUE  ( 0x0 )
#define CE_VOIP_CFG_MAILBOX_HSTS_COM_RD_DEFAULT_VALUE             ( 0x0 )
#define CE_VOIP_CFG_MAILBOX_HSTS_COM_RD_DEFAULT_VALUE_RESET_VALUE ( 0x0 )
#define CE_VOIP_CFG_MAILBOX_HSTS_REP_WR_DEFAULT_VALUE             ( 0x0 )
#define CE_VOIP_CFG_MAILBOX_HSTS_REP_WR_DEFAULT_VALUE_RESET_VALUE ( 0x0 )


#define CE_VOIP_CFG_MAILBOX_HSTS_OFFSET ( 0x00000020 )

#define CE_VOIP_CFG_MAILBOX_HSTS_ADDRESS   	( CE_VOIP_CFG_MAILBOX_ADDRESS + CE_VOIP_CFG_MAILBOX_HSTS_OFFSET )
#define BL_VOIP_CFG_MAILBOX_HSTS_READ( r ) 	BL_READ_32( ( CE_VOIP_CFG_MAILBOX_HSTS_ADDRESS ), (r) )
#define BL_VOIP_CFG_MAILBOX_HSTS_WRITE( v )	BL_WRITE_32( ( CE_VOIP_CFG_MAILBOX_HSTS_ADDRESS ), (v) )

typedef struct
{
	/* RSV */
	stt_uint32 rsv   	: 26 __PACKING_ATTRIBUTE_FIELD_LEVEL__ ;

	/* HBUSY */
	stt_uint32 dbusy 	: 1 __PACKING_ATTRIBUTE_FIELD_LEVEL__ ;

	/* WRERR */
	stt_uint32 wrerr 	: 1 __PACKING_ATTRIBUTE_FIELD_LEVEL__ ;

	/* COM_RD */
	stt_uint32 com_rd	: 2 __PACKING_ATTRIBUTE_FIELD_LEVEL__ ;

	/* REP_WR */
	stt_uint32 rep_wr	: 2 __PACKING_ATTRIBUTE_FIELD_LEVEL__ ;
}
__PACKING_ATTRIBUTE_STRUCT_END__
VOIP_CFG_MAILBOX_HSTS_DTE ;


/*****************************************************************************************/
/* IRQ_EN                                                                                */
/* Interrupt enable                                                                      */
/*****************************************************************************************/

#define CE_VOIP_CFG_MAILBOX_IRQ_EN_RSV_DEFAULT_VALUE                      ( 0x0 )
#define CE_VOIP_CFG_MAILBOX_IRQ_EN_RSV_DEFAULT_VALUE_RESET_VALUE          ( 0x0 )
#define CE_VOIP_CFG_MAILBOX_IRQ_EN_WRERR_INT_EN_DEFAULT_VALUE             ( 0x0 )
#define CE_VOIP_CFG_MAILBOX_IRQ_EN_WRERR_INT_EN_DEFAULT_VALUE_RESET_VALUE ( 0x0 )
#define CE_VOIP_CFG_MAILBOX_IRQ_EN_COM_INT_EN_DEFAULT_VALUE               ( 0x0 )
#define CE_VOIP_CFG_MAILBOX_IRQ_EN_COM_INT_EN_DEFAULT_VALUE_RESET_VALUE   ( 0x0 )
#define CE_VOIP_CFG_MAILBOX_IRQ_EN_REP_INT_EN_DEFAULT_VALUE               ( 0x0 )
#define CE_VOIP_CFG_MAILBOX_IRQ_EN_REP_INT_EN_DEFAULT_VALUE_RESET_VALUE   ( 0x0 )
#define CE_VOIP_CFG_MAILBOX_IRQ_EN_SEM_INT_EN_DEFAULT_VALUE               ( 0x0 )
#define CE_VOIP_CFG_MAILBOX_IRQ_EN_SEM_INT_EN_DEFAULT_VALUE_RESET_VALUE   ( 0x0 )


#define CE_VOIP_CFG_MAILBOX_IRQ_EN_OFFSET ( 0x00000024 )

#define CE_VOIP_CFG_MAILBOX_IRQ_EN_ADDRESS   	( CE_VOIP_CFG_MAILBOX_ADDRESS + CE_VOIP_CFG_MAILBOX_IRQ_EN_OFFSET )
#define BL_VOIP_CFG_MAILBOX_IRQ_EN_READ( r ) 	BL_READ_32( ( CE_VOIP_CFG_MAILBOX_IRQ_EN_ADDRESS ), (r) )
#define BL_VOIP_CFG_MAILBOX_IRQ_EN_WRITE( v )	BL_WRITE_32( ( CE_VOIP_CFG_MAILBOX_IRQ_EN_ADDRESS ), (v) )

typedef struct
{
	/* RSV */
	stt_uint32 rsv         	: 19 __PACKING_ATTRIBUTE_FIELD_LEVEL__ ;

	/* WRERR_INT_EN */
	stt_uint32 wrerr_int_en	: 1 __PACKING_ATTRIBUTE_FIELD_LEVEL__ ;

	/* COM_INT_EN */
	stt_uint32 com_int_en  	: 2 __PACKING_ATTRIBUTE_FIELD_LEVEL__ ;

	/* REP_INT_EN */
	stt_uint32 rep_int_en  	: 2 __PACKING_ATTRIBUTE_FIELD_LEVEL__ ;

	/* SEM_INT_EN */
	stt_uint32 sem_int_en  	: 8 __PACKING_ATTRIBUTE_FIELD_LEVEL__ ;
}
__PACKING_ATTRIBUTE_STRUCT_END__
VOIP_CFG_MAILBOX_IRQ_EN_DTE ;


/*****************************************************************************************/
/* IRQ_STATUS                                                                            */
/* Status of interrupts                                                                  */
/*****************************************************************************************/

#define CE_VOIP_CFG_REGS_IRQ_STATUS_RSV_DEFAULT_VALUE                   ( 0x0 )
#define CE_VOIP_CFG_REGS_IRQ_STATUS_RSV_DEFAULT_VALUE_RESET_VALUE       ( 0x0 )
#define CE_VOIP_CFG_REGS_IRQ_STATUS_WRERR_IRQ_ACTIVE_VALUE              ( 0x1 )
#define CE_VOIP_CFG_REGS_IRQ_STATUS_WRERR_IRQ_ACTIVE_VALUE_RESET_VALUE  ( 0x1 )
#define CE_VOIP_CFG_REGS_IRQ_STATUS_COMREP_IRQ_ACTIVE_VALUE             ( 0x1 )
#define CE_VOIP_CFG_REGS_IRQ_STATUS_COMREP_IRQ_ACTIVE_VALUE_RESET_VALUE ( 0x1 )
#define CE_VOIP_CFG_REGS_IRQ_STATUS_DSEM_IRQ_ACTIVE_VALUE               ( 0x1 )
#define CE_VOIP_CFG_REGS_IRQ_STATUS_DSEM_IRQ_ACTIVE_VALUE_RESET_VALUE   ( 0x1 )


#define CE_VOIP_CFG_REGS_IRQ_STATUS_OFFSET ( 0x00000000 )

#define CE_VOIP_CFG_REGS_IRQ_STATUS_ADDRESS   	( CE_VOIP_CFG_REGS_ADDRESS + CE_VOIP_CFG_REGS_IRQ_STATUS_OFFSET )
#define BL_VOIP_CFG_REGS_IRQ_STATUS_READ( r ) 	BL_READ_32( ( CE_VOIP_CFG_REGS_IRQ_STATUS_ADDRESS ), (r) )
#define BL_VOIP_CFG_REGS_IRQ_STATUS_WRITE( v )	BL_WRITE_32( ( CE_VOIP_CFG_REGS_IRQ_STATUS_ADDRESS ), (v) )

typedef struct
{
	/* RESERVED */
	stt_uint32 rsv       	: 29 __PACKING_ATTRIBUTE_FIELD_LEVEL__ ;

	/* WRERR_IRQ */
	stt_uint32 wrerr_irq 	: 1 __PACKING_ATTRIBUTE_FIELD_LEVEL__ ;

	/* COMREP_IRQ */
	stt_uint32 comrep_irq	: 1 __PACKING_ATTRIBUTE_FIELD_LEVEL__ ;

	/* DSEM_IRQ */
	stt_uint32 dsem_irq  	: 1 __PACKING_ATTRIBUTE_FIELD_LEVEL__ ;
}
__PACKING_ATTRIBUTE_STRUCT_END__
VOIP_CFG_REGS_IRQ_STATUS_DTE ;


/*****************************************************************************************/
/* IRQ_CFG                                                                               */
/* IRQ configuration for testing                                                         */
/*****************************************************************************************/

#define CE_VOIP_CFG_REGS_IRQ_CFG_R1_DEFAULT_VALUE                     ( 0x0 )
#define CE_VOIP_CFG_REGS_IRQ_CFG_R1_DEFAULT_VALUE_RESET_VALUE         ( 0x0 )
#define CE_VOIP_CFG_REGS_IRQ_CFG_TEST_VALUE_DEFAULT_VALUE             ( 0x0 )
#define CE_VOIP_CFG_REGS_IRQ_CFG_TEST_VALUE_DEFAULT_VALUE_RESET_VALUE ( 0x0 )
#define CE_VOIP_CFG_REGS_IRQ_CFG_TEST_MODE_DEFAULT_VALUE              ( 0x0 )
#define CE_VOIP_CFG_REGS_IRQ_CFG_TEST_MODE_DEFAULT_VALUE_RESET_VALUE  ( 0x0 )


#define CE_VOIP_CFG_REGS_IRQ_CFG_OFFSET ( 0x00000004 )

#define CE_VOIP_CFG_REGS_IRQ_CFG_ADDRESS   	( CE_VOIP_CFG_REGS_ADDRESS + CE_VOIP_CFG_REGS_IRQ_CFG_OFFSET )
#define BL_VOIP_CFG_REGS_IRQ_CFG_READ( r ) 	BL_READ_32( ( CE_VOIP_CFG_REGS_IRQ_CFG_ADDRESS ), (r) )
#define BL_VOIP_CFG_REGS_IRQ_CFG_WRITE( v )	BL_WRITE_32( ( CE_VOIP_CFG_REGS_IRQ_CFG_ADDRESS ), (v) )

typedef struct
{
	/* RESERVED */
	stt_uint32 r1        	: 28 __PACKING_ATTRIBUTE_FIELD_LEVEL__ ;

	/* TEST_VALUE */
	stt_uint32 test_value	: 3 __PACKING_ATTRIBUTE_FIELD_LEVEL__ ;

	/* TEST_MODE */
	stt_uint32 test_mode 	: 1 __PACKING_ATTRIBUTE_FIELD_LEVEL__ ;
}
__PACKING_ATTRIBUTE_STRUCT_END__
VOIP_CFG_REGS_IRQ_CFG_DTE ;


/*****************************************************************************************/
/* CEVA_STATUS                                                                           */
/* Allows read of CEVA output signals                                                    */
/*****************************************************************************************/

#define CE_VOIP_CFG_REGS_CEVA_STATUS_R1_DEFAULT_VALUE               ( 0x0 )
#define CE_VOIP_CFG_REGS_CEVA_STATUS_R1_DEFAULT_VALUE_RESET_VALUE   ( 0x0 )
#define CE_VOIP_CFG_REGS_CEVA_STATUS_DATA_DEFAULT_VALUE             ( 0x0 )
#define CE_VOIP_CFG_REGS_CEVA_STATUS_DATA_DEFAULT_VALUE_RESET_VALUE ( 0x0 )


#define CE_VOIP_CFG_REGS_CEVA_STATUS_OFFSET ( 0x00000008 )

#define CE_VOIP_CFG_REGS_CEVA_STATUS_ADDRESS   	( CE_VOIP_CFG_REGS_ADDRESS + CE_VOIP_CFG_REGS_CEVA_STATUS_OFFSET )
#define BL_VOIP_CFG_REGS_CEVA_STATUS_READ( r ) 	BL_READ_32( ( CE_VOIP_CFG_REGS_CEVA_STATUS_ADDRESS ), (r) )
#define BL_VOIP_CFG_REGS_CEVA_STATUS_WRITE( v )	BL_WRITE_32( ( CE_VOIP_CFG_REGS_CEVA_STATUS_ADDRESS ), (v) )

typedef struct
{
	/* RESERVED */
	stt_uint32 r1  	: 25 __PACKING_ATTRIBUTE_FIELD_LEVEL__ ;

	/* DATA */
	stt_uint32 data	: 7 __PACKING_ATTRIBUTE_FIELD_LEVEL__ ;
}
__PACKING_ATTRIBUTE_STRUCT_END__
VOIP_CFG_REGS_CEVA_STATUS_DTE ;


/*****************************************************************************************/
/* CEVA_CFG                                                                              */
/* Allows configuration of CEVA input signals                                            */
/*****************************************************************************************/

#define CE_VOIP_CFG_REGS_CEVA_CFG_R1_DEFAULT_VALUE                          ( 0x0 )
#define CE_VOIP_CFG_REGS_CEVA_CFG_R1_DEFAULT_VALUE_RESET_VALUE              ( 0x0 )
#define CE_VOIP_CFG_REGS_CEVA_CFG_INVERT_GPIO_OEN_DEFAULT_VALUE             ( 0x0 )
#define CE_VOIP_CFG_REGS_CEVA_CFG_INVERT_GPIO_OEN_DEFAULT_VALUE_RESET_VALUE ( 0x0 )
#define CE_VOIP_CFG_REGS_CEVA_CFG_TIE_LS_TO_ZERO_DEFAULT_VALUE              ( 0x0 )
#define CE_VOIP_CFG_REGS_CEVA_CFG_TIE_LS_TO_ZERO_DEFAULT_VALUE_RESET_VALUE  ( 0x0 )
#define CE_VOIP_CFG_REGS_CEVA_CFG_DATA_DEFAULT_VALUE                        ( 0x0 )
#define CE_VOIP_CFG_REGS_CEVA_CFG_DATA_DEFAULT_VALUE_RESET_VALUE            ( 0x0 )


#define CE_VOIP_CFG_REGS_CEVA_CFG_OFFSET ( 0x0000000C )

#define CE_VOIP_CFG_REGS_CEVA_CFG_ADDRESS   	( CE_VOIP_CFG_REGS_ADDRESS + CE_VOIP_CFG_REGS_CEVA_CFG_OFFSET )
#define BL_VOIP_CFG_REGS_CEVA_CFG_READ( r ) 	BL_READ_32( ( CE_VOIP_CFG_REGS_CEVA_CFG_ADDRESS ), (r) )
#define BL_VOIP_CFG_REGS_CEVA_CFG_WRITE( v )	BL_WRITE_32( ( CE_VOIP_CFG_REGS_CEVA_CFG_ADDRESS ), (v) )

typedef struct
{
	/* RESERVED */
	stt_uint32 r1             	: 13 __PACKING_ATTRIBUTE_FIELD_LEVEL__ ;

	/* INVERT_GPIO_OEN */
	stt_uint32 invert_gpio_oen	: 1 __PACKING_ATTRIBUTE_FIELD_LEVEL__ ;

	/* TIE_LS_TO_ZERO */
	stt_uint32 tie_ls_to_zero 	: 1 __PACKING_ATTRIBUTE_FIELD_LEVEL__ ;

	/* DATA */
	stt_uint32 data           	: 17 __PACKING_ATTRIBUTE_FIELD_LEVEL__ ;
}
__PACKING_ATTRIBUTE_STRUCT_END__
VOIP_CFG_REGS_CEVA_CFG_DTE ;


/*****************************************************************************************/
/* VERSION                                                                               */
/* Configures version ID for CEVA                                                        */
/*****************************************************************************************/

#define CE_VOIP_CFG_REGS_VERSION_RSV_DEFAULT_VALUE             ( 0x0 )
#define CE_VOIP_CFG_REGS_VERSION_RSV_DEFAULT_VALUE_RESET_VALUE ( 0x0 )
#define CE_VOIP_CFG_REGS_VERSION_VAL_DEFAULT_VALUE             ( 0x0 )
#define CE_VOIP_CFG_REGS_VERSION_VAL_DEFAULT_VALUE_RESET_VALUE ( 0x0 )


#define CE_VOIP_CFG_REGS_VERSION_OFFSET ( 0x00000010 )

#define CE_VOIP_CFG_REGS_VERSION_ADDRESS   	( CE_VOIP_CFG_REGS_ADDRESS + CE_VOIP_CFG_REGS_VERSION_OFFSET )
#define BL_VOIP_CFG_REGS_VERSION_READ( r ) 	BL_READ_32( ( CE_VOIP_CFG_REGS_VERSION_ADDRESS ), (r) )
#define BL_VOIP_CFG_REGS_VERSION_WRITE( v )	BL_WRITE_32( ( CE_VOIP_CFG_REGS_VERSION_ADDRESS ), (v) )

typedef struct
{
	/* RESERVED */
	stt_uint32 rsv	: 26 __PACKING_ATTRIBUTE_FIELD_LEVEL__ ;

	/* VAL */
	stt_uint32 val	: 6 __PACKING_ATTRIBUTE_FIELD_LEVEL__ ;
}
__PACKING_ATTRIBUTE_STRUCT_END__
VOIP_CFG_REGS_VERSION_DTE ;


/*****************************************************************************************/
/* BOOT_ADDR                                                                             */
/* Configures CEVA boot address                                                          */
/*****************************************************************************************/

#define CE_VOIP_CFG_REGS_BOOT_ADDR_VAL_DEFAULT_VALUE             ( 0x0 )
#define CE_VOIP_CFG_REGS_BOOT_ADDR_VAL_DEFAULT_VALUE_RESET_VALUE ( 0x0 )


#define CE_VOIP_CFG_REGS_BOOT_ADDR_OFFSET ( 0x00000014 )

#define CE_VOIP_CFG_REGS_BOOT_ADDR_ADDRESS   	( CE_VOIP_CFG_REGS_ADDRESS + CE_VOIP_CFG_REGS_BOOT_ADDR_OFFSET )
#define BL_VOIP_CFG_REGS_BOOT_ADDR_READ( r ) 	BL_READ_32( ( CE_VOIP_CFG_REGS_BOOT_ADDR_ADDRESS ), (r) )
#define BL_VOIP_CFG_REGS_BOOT_ADDR_WRITE( v )	BL_WRITE_32( ( CE_VOIP_CFG_REGS_BOOT_ADDR_ADDRESS ), (v) )

typedef struct
{
	/* VAL */
	stt_uint32 val	: 32 __PACKING_ATTRIBUTE_FIELD_LEVEL__ ;
}
__PACKING_ATTRIBUTE_STRUCT_END__
VOIP_CFG_REGS_BOOT_ADDR_DTE ;


/*****************************************************************************************/
/* CLEAR_STICKY                                                                          */
/* Clear pi_ack sticky bit                                                               */
/*****************************************************************************************/

#define CE_VOIP_CFG_REGS_CLEAR_STICKY_RSV_DEFAULT_VALUE             ( 0x0 )
#define CE_VOIP_CFG_REGS_CLEAR_STICKY_RSV_DEFAULT_VALUE_RESET_VALUE ( 0x0 )
#define CE_VOIP_CFG_REGS_CLEAR_STICKY_VAL_DEFAULT_VALUE             ( 0x0 )
#define CE_VOIP_CFG_REGS_CLEAR_STICKY_VAL_DEFAULT_VALUE_RESET_VALUE ( 0x0 )


#define CE_VOIP_CFG_REGS_CLEAR_STICKY_OFFSET ( 0x00000018 )

#define CE_VOIP_CFG_REGS_CLEAR_STICKY_ADDRESS   	( CE_VOIP_CFG_REGS_ADDRESS + CE_VOIP_CFG_REGS_CLEAR_STICKY_OFFSET )
#define BL_VOIP_CFG_REGS_CLEAR_STICKY_READ( r ) 	BL_READ_32( ( CE_VOIP_CFG_REGS_CLEAR_STICKY_ADDRESS ), (r) )
#define BL_VOIP_CFG_REGS_CLEAR_STICKY_WRITE( v )	BL_WRITE_32( ( CE_VOIP_CFG_REGS_CLEAR_STICKY_ADDRESS ), (v) )

typedef struct
{
	/* RESERVED */
	stt_uint32 rsv	: 31 __PACKING_ATTRIBUTE_FIELD_LEVEL__ ;

	/* CLR */
	stt_uint32 val	: 1 __PACKING_ATTRIBUTE_FIELD_LEVEL__ ;
}
__PACKING_ATTRIBUTE_STRUCT_END__
VOIP_CFG_REGS_CLEAR_STICKY_DTE ;


/*****************************************************************************************/
/* AHB_CFG                                                                               */
/* AHB bridge configuration registers                                                    */
/*****************************************************************************************/

#define CE_VOIP_CFG_REGS_AHB_CFG_VAL_DEFAULT_VALUE             ( 0x0 )
#define CE_VOIP_CFG_REGS_AHB_CFG_VAL_DEFAULT_VALUE_RESET_VALUE ( 0x0 )


#define CE_VOIP_CFG_REGS_AHB_CFG_OFFSET ( 0x00000024 )

#define CE_VOIP_CFG_REGS_AHB_CFG_ADDRESS        	( CE_VOIP_CFG_REGS_ADDRESS + CE_VOIP_CFG_REGS_AHB_CFG_OFFSET )
#define BL_VOIP_CFG_REGS_AHB_CFG_READ_I( r, i ) 	BL_READ_I_32( ( CE_VOIP_CFG_REGS_AHB_CFG_ADDRESS ), (i), (r) )
#define BL_VOIP_CFG_REGS_AHB_CFG_WRITE_I( v, i )	BL_WRITE_I_32( ( CE_VOIP_CFG_REGS_AHB_CFG_ADDRESS ), (i), (v) )

typedef struct
{
	/* VALUE */
	stt_uint32 val	: 32 __PACKING_ATTRIBUTE_FIELD_LEVEL__ ;
}
__PACKING_ATTRIBUTE_STRUCT_END__
VOIP_CFG_REGS_AHB_CFG_DTE ;


typedef struct
{
	/* COM0 */
	VOIP_CFG_MAILBOX_COM0_DTE com0 __PACKING_ATTRIBUTE_FIELD_LEVEL__ ;

	/* COM1 */
	VOIP_CFG_MAILBOX_COM1_DTE com1 __PACKING_ATTRIBUTE_FIELD_LEVEL__ ;

	/* REP0 */
	VOIP_CFG_MAILBOX_REP0_DTE rep0 __PACKING_ATTRIBUTE_FIELD_LEVEL__ ;

	/* REP1 */
	VOIP_CFG_MAILBOX_REP1_DTE rep1 __PACKING_ATTRIBUTE_FIELD_LEVEL__ ;

	/* DSEM */
	VOIP_CFG_MAILBOX_DSEM_DTE dsem __PACKING_ATTRIBUTE_FIELD_LEVEL__ ;

	/* HSEM */
	VOIP_CFG_MAILBOX_HSEM_DTE hsem __PACKING_ATTRIBUTE_FIELD_LEVEL__ ;

	/* HSEM_SET */
	VOIP_CFG_MAILBOX_HSEM_SET_DTE hsem_set __PACKING_ATTRIBUTE_FIELD_LEVEL__ ;

	/* HSEM_CLR */
	VOIP_CFG_MAILBOX_HSEM_CLR_DTE hsem_clr __PACKING_ATTRIBUTE_FIELD_LEVEL__ ;

	/* HSTS */
	VOIP_CFG_MAILBOX_HSTS_DTE hsts __PACKING_ATTRIBUTE_FIELD_LEVEL__ ;

	/* IRQ_EN */
	VOIP_CFG_MAILBOX_IRQ_EN_DTE irq_en __PACKING_ATTRIBUTE_FIELD_LEVEL__ ;
}
 __PACKING_ATTRIBUTE_STRUCT_END__
VOIP_CFG_MAILBOX_DTE ;

/*****************************************************************************************/
/* VoIP configuration and status                                                         */
/*****************************************************************************************/

/*****************************************************************************************/
/* Registers array numbers                                                               */
/*****************************************************************************************/
#define CE_VOIP_CFG_AHB_CFG_NUMBER ( 16 )
typedef struct
{
	/* IRQ_STATUS */
	VOIP_CFG_REGS_IRQ_STATUS_DTE irq_status __PACKING_ATTRIBUTE_FIELD_LEVEL__ ;

	/* IRQ_CFG */
	VOIP_CFG_REGS_IRQ_CFG_DTE irq_cfg __PACKING_ATTRIBUTE_FIELD_LEVEL__ ;

	/* CEVA_STATUS */
	VOIP_CFG_REGS_CEVA_STATUS_DTE ceva_status __PACKING_ATTRIBUTE_FIELD_LEVEL__ ;

	/* CEVA_CFG */
	VOIP_CFG_REGS_CEVA_CFG_DTE ceva_cfg __PACKING_ATTRIBUTE_FIELD_LEVEL__ ;

	/* VERSION */
	VOIP_CFG_REGS_VERSION_DTE version __PACKING_ATTRIBUTE_FIELD_LEVEL__ ;

	/* BOOT_ADDR */
	VOIP_CFG_REGS_BOOT_ADDR_DTE boot_addr __PACKING_ATTRIBUTE_FIELD_LEVEL__ ;

	/* CLEAR_STICKY */
	VOIP_CFG_REGS_CLEAR_STICKY_DTE clear_sticky __PACKING_ATTRIBUTE_FIELD_LEVEL__ ;

	/* Reserved */
	stt_uint8 reserved1 [ 8 ] __PACKING_ATTRIBUTE_FIELD_LEVEL__ ;

	/* AHB_CFG */
	VOIP_CFG_REGS_AHB_CFG_DTE ahb_cfg [ CE_VOIP_CFG_AHB_CFG_NUMBER ] __PACKING_ATTRIBUTE_FIELD_LEVEL__ ;
}
 __PACKING_ATTRIBUTE_STRUCT_END__
VOIP_CFG_REGS_DTE ;

typedef struct
{
	/* mailbox function */
	VOIP_CFG_MAILBOX_DTE mailbox __PACKING_ATTRIBUTE_FIELD_LEVEL__ ;

	/* Reserved */
	stt_uint8 reserved0 [ 88 ] __PACKING_ATTRIBUTE_FIELD_LEVEL__ ;

	/* regs function */
	VOIP_CFG_REGS_DTE regs __PACKING_ATTRIBUTE_FIELD_LEVEL__ ;
}
 __PACKING_ATTRIBUTE_STRUCT_END__
VOIP_CFG_DTE ;

typedef struct
{
	/* CFG */
	VOIP_CFG_DTE cfg __PACKING_ATTRIBUTE_FIELD_LEVEL__ ;
}
__PACKING_ATTRIBUTE_STRUCT_END__ 
VOIP_DTE ;
#endif /* VOIP_H_INCLUDED */

