/*
* <:copyright-BRCM:2012:DUAL/GPL:standard
* 
*    Copyright (c) 2012 Broadcom Corporation
*    All Rights Reserved
* 
* This program is free software; you can redistribute it and/or modify
* it under the terms of the GNU General Public License, version 2, as published by
* the Free Software Foundation (the "GPL").
* 
* This program is distributed in the hope that it will be useful,
* but WITHOUT ANY WARRANTY; without even the implied warranty of
* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
* GNU General Public License for more details.
* 
* 
* A copy of the GPL is available at http://www.broadcom.com/licenses/GPLv2.php, or by
* writing to the Free Software Foundation, Inc., 59 Temple Place - Suite 330,
* Boston, MA 02111-1307, USA.
* 
* :> 
*/

/**** This is an autogenerated file with definitions common to FW and SW ****/

#ifndef _BL_RNR_IH_DEFS_H
#define _BL_RNR_IH_DEFS_H


/* not in use in 1st phase */
#define LILAC_DRV_RDD_IH_RUNNER_0_IH_RESPONSE_ADDRESS   ( 0xB6F0 )
#define LILAC_DRV_RDD_IH_RUNNER_1_IH_RESPONSE_ADDRESS   ( 0xB6F0 )
/* not in use in 1st phase */
#define LILAC_DRV_RDD_IH_RUNNER_0_IH_CONGESTION_REPORT_ADDRESS   ( 0 )/* constant */
#define LILAC_DRV_RDD_IH_RUNNER_1_IH_CONGESTION_REPORT_ADDRESS   ( 0 )/* constant */

/* not in use in 1st phase */
#define LILAC_DRV_RDD_IH_RUNNER_0_IH_CONGESTION_REPORT_ENABLE   ( 0 )/* constant */
#define LILAC_DRV_RDD_IH_RUNNER_1_IH_CONGESTION_REPORT_ENABLE   ( 0 )/* constant */

#define LILAC_DRV_RDD_IH_RUNNER_0_IH_MANAGED_RB_BASE_ADDRESS   ( 0x0 )
#define LILAC_DRV_RDD_IH_RUNNER_1_IH_MANAGED_RB_BASE_ADDRESS   ( 0x0 )

/* not in use in 1st phase */
#define LILAC_DRV_RDD_IH_RUNNER_0_RUNNER_MANAGED_RB_BASE_ADDRESS   ( 0 )/* constant */
#define LILAC_DRV_RDD_IH_RUNNER_1_RUNNER_MANAGED_RB_BASE_ADDRESS   ( 0 )/* constant */

#define LILAC_DRV_RDD_IH_CAM_SEARCH_ENABLE_UPON_INVALID_LUT_ENTRY   ( 0 )/* constant */

/* common for all ports */
#define LILAC_DRV_RDD_IH_PACKET_HEADER_OFFSET   ( 18 )
#define LILAC_DRV_RDD_IH_US_DEFAULT_RUNNER   ( DRV_IH_RUNNER_CLUSTER_B )/* constant */

#endif /* _BL_RNR_IH_DEFS_H */


